version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mentiis
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - ../app:/app
    networks:
      - mentiis-network
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mentiis
    ports:
      - "5432:5432"
    networks:
      - mentiis-network
    restart: unless-stopped
volumes:
  postgres_data:

networks:
  mentiis-network:
    driver: bridge
